server:
  port: 8082
  
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://10.119.162.25;databaseName=customer
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true
    username: "{cipher}51123f6544187d5187ff252a981dee36bde60da30086867ac0d7883a5bfa2cee"
    password: "{cipher}51123f6544187d5187ff252a981dee36bde60da30086867ac0d7883a5bfa2cee"
    driver-class-name: com.mysql.jdbc.Driver
    
