server:
  port: 9090
  
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customer/**
      - id: product-catalogue
        uri: lb://PRODUCT-CATALOGUE
        predicates:
        - Path=/product/**
      - id: delivery-service
        uri: lb://DELIVERY-SERVICE
        predicates:
        - Path=/delivery/**
      - id: inventory-service
        uri: lb://INVENTORY-SERVICE
        predicates:
        - Path=/inventory/**
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
