server:
  port: 8085
  
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
 
#MySQL DB setup 
#spring:
#  jpa:
#    #generate-ddl: true
#    hibernate:
#      ddl-auto: update
 # datasource:
  #  #url: jdbc:sqlserver://10.119.162.25;databaseName=order
   # url: jdbc:mysql://localhost:3306/order?createDatabaseIfNotExist=true
    #username: "{cipher}51123f6544187d5187ff252a981dee36bde60da30086867ac0d7883a5bfa2cee"
    #password: "{cipher}51123f6544187d5187ff252a981dee36bde60da30086867ac0d7883a5bfa2cee"
    #driver-class-name: com.mysql.cj.jdbc.Driver
    
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
        hibernate.default_schema: eventuate
        hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eventuate?useSSL=false
    username: postgres
    password: admin
    
eventuate:
    database: 
        schema: eventuate

